### ISSUE TITLE
Lỗi thêm ca sĩ

### ISSUE THREAD

**Issue by tinhcavn** [hoaquynhtim99/music#11]
Lỗi khi thêm ca sĩ có năm sinh lớn, cụ thể thêm ca sĩ Lý Hải sinh ngày 28/09/1968 thì bị lỗi: "Lỗi lưu dữ liệu: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'artist_birthday' at row 1"

**Comment by tinhcavn** [comment]
Đã sửa được lỗi, chỉ cần thay đổi cấu trúc SQL từ:

`artist_birthday int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'Sinh nhật',`

sang:

`artist_birthday int(11) NOT NULL COMMENT 'Sinh nhật',`

**Comment by hoaquynhtim99** [comment]
@tinhcavn ra ngoài site nó có hiển thị đúng năm như đã thêm trong quản trị ko bạn

**Comment by tinhcavn** [comment]
gọi $artist_birthday ra site bằng hàm date() thì đúng, mình chỉnh sửa theo module users

**Comment by tinhcavn** [comment]
mong bạn sớm hoàn thành chức năng chỉnh sửa playlist, có thêm funs gọi playlist khi không là thành viên nữa. Tks for your project.
