### ISSUE TITLE
Khi cho chay trên nukeviet 4.1beta1 thì báo lỗi trắng màn hình mất quyền đăng nhập admin luôn

### ISSUE THREAD

**Issue by matbuonvn** [hoaquynhtim99/music#2]
Bác cho em hỏi module music ấy có chạy được trên nukeviet 4.1beta1 ko ạ. Mà sao khi em cài lên thì mất luôn quyền truy cập admin luôn ạ

**Comment by hoaquynhtim99** [comment]
Module chưa có phiên bản cho NukeViet 4 nha bạn
