### ISSUE TITLE
Xin số điện thoại để làm code music cho nukeviet 4.1beta1

### ISSUE THREAD

**Issue by matbuonvn** [hoaquynhtim99/music#3]
Bác cho em xin số điện thoại để thương lượng với bác làm module music cho nuke 4.1beta1
fb: http://facebook.com/nguoiduoimua
sô di động: 0964. 596. 550
web: http://matbuon.vn

**Comment by hoaquynhtim99** [comment]
Chào bạn, music là một dự án rất lớn, người thành thục code phải làm liên tục khoảng hơn 30 công mới có thể chạy tạm ổn. Do đó mình sẽ không nhận dự án này với bất kỳ giá cả thế nào. Hiện mình không có nhiều thời gian rảnh. Bạn có thể tìm tổ chức hoặc cá nhân khác
