### ISSUE TITLE
Đề xuất dùng APlayer cho phần play audio 

### ISSUE THREAD

**Issue by tuannvbg** [hoaquynhtim99/music#7]
Aplayer HTML5 có chức năng hỗ trợ lời bài hát karaoke như Zing HTML5 Player

**Comment by quoctiepkt** [comment]
chạy lời bài hát như zing cũng hay, bản mới e xem thử chức năng nghe hết một bài hát là nó tự động next qua bài hát khác cùng thể loại. chức năng đó rất hay, mọi người có thể nghe liên tục.

**Comment by Quoctiepkontum** [comment]
chạy lời bài hát như zing cũng hay, bản mới e xem thử chức năng nghe hết một bài hát là nó tự động next qua bài hát khác cùng thể loại. chức năng đó rất hay, mọi người có thể nghe liên tục.

**Comment by hoaquynhtim99** [comment]
Module music 4 sẽ có phần hiển thị lời tuy nhiên vẫn dùng jwplayer. APlayer không thể nào thay thế Jwplayer được
