### ISSUE TITLE
Hiển thị lịch sử thêm ca sĩ lần trước

### ISSUE THREAD

**Issue by quoctiepkt** [hoaquynhtim99/music#9]
![66](https://user-images.githubusercontent.com/4196668/62866637-84c90f00-bd3b-11e9-93c8-2c3bf9073a12.jpg)

a làm bữa giờ, có một chỗ thêm tên ca sĩ, mình mà thêm dc lịch sử chọn ca sĩ lần trước là y bài ak e
a thêm 10 bài hát của ca sĩ đó, lúc thêm bài hát phải tìm ca sĩ đó, giờ hiển thị lịch sử của ca sĩ thêm lần trước là tuyệt vời luôn e

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/hoaquynhtim99/music/commit/fe2e3f1c1bd2632b3f194a36aeefb6bf15020e20 
![08-11-2019 8-31-04 SA](https://user-images.githubusercontent.com/2421714/68441979-55bf1e00-0202-11ea-8eda-065939bac738.png)
